---
- name: Display Role Details.
  debug:
    msg:
      - '===================================================================='
      - 'constrict0r.devels'
      - 'Apply developer configuration.'
      - '===================================================================='
